#!/bin/bash

config_dir=/config
work_dir=/work
app_dir=/app
nginx_dir=/etc/nginx/

if [ -e "${config_dir}/server.crt" ]; then
    cp ${config_dir}/server.crt ${work_dir}/server.crt
fi;

if [ -e "${config_dir}/server.key" ]; then
    cp ${config_dir}/server.key ${work_dir}/server.key
fi;

if [ -e "${config_dir}/hitideConfig.js" ]; then
    cp ${config_dir}/hitideConfig.js ${app_dir}/hitideConfig.js
fi;

if [ -e "${config_dir}/nginx.conf" ]; then
    cp ${config_dir}/nginx.conf ${nginx_dir}/nginx.conf
fi;

nginx -g "daemon off;"
